### ISSUE TITLE
Group-analysis using LST-AI output

### ISSUE THREAD

**Issue by MMSchmitgen** [CompImg/LST-AI#15]
Not an issue, but some questions.

1. Are the *.nii.gz output-files from LST-AI in MNI space, when using LST-AI with default settings? From reading your preprint on LST-AI (https://doi.org/10.1101/2023.11.23.23298966) this is not clear to me.
2. I would like to use the *seg-lst.nii.gz output images for whole-brain group comparisons. I tried setting up a 2nd-level model in SPM (after decompressing the *.nii.gz files), but SPM drops an error using spm_check_orientations: "The orientations etc must be identical for this procedure.". Any suggestions on how I could perform whole-brain group comparisons using LST-AI output?

Cheers and thanks a lot,
Mike

**Comment by twiltgen** [comment]
Hi Mike,

I hope I can address your questions:
1) The default output file of LST-AI is the lesion mask in the FLAIR image space "space-flair_seg-lst.nii.gz". If you use the "--temp path/to/temp/folder" flag, then also the auxiliary files generated during processing will be saved, including the lesion mask in MNI space "sub-X_ses-Y_space-mni_seg-lst.nii.gz". 
2) I guess you have used the default (decompressed) "space-flair_seg-lst.nii.gz" output to run the group comparison with SPM? Maybe you can try it with the "space-mni_seg-lst.nii.gz" lesion masks, which will be available after running LST-AI with the "--temp" flag. They should all be in the same image space and have the same orientation.

Cheers, and let me know if this helps.
Tun

**Comment by MMSchmitgen** [comment]
Hi Tun,

thanks a lot for your quick reply.
Ah, I see. I will give it a shot and keep you updated (might take some days, though).

Cheers,
Mike

**Comment by MMSchmitgen** [comment]
Hi Tun,

it worked like a charm. 
Thank you so much for your help. :)

Cheers and have a nice weekend,
Mike
