### ISSUE TITLE
Is noise/motion in FLAIR and T1 a problem?

### ISSUE THREAD

**Issue by MMSchmitgen** [CompImg/LST-AI#16]
Hi everyone,

having a closer look at my data, I started wondering, if and to which extent noise/motion in FLAIR and/or T1 images have an effect on performance of LST-AI?
Is there any procedure you would recommend to identify subjects to exclude from analysis using LST-AI because of insufficient data-quality?

Cheers and thanks a lot,
Mike

**Comment by jqmcginnis** [comment]
Hi @MMSchmitgen,

Thanks for the question :slightly_smiling_face: 

We have not explicitly tested for motion artifacts and noise in scans in the paper.

Concerning motion, we are insensitive to inter-scan movement, i.e. movement between different acquired contrasts, given that we register the scans (rigidly) before they go into the CNN. Regarding intra-scan motion (i.e., artifacts in the scan), we have no inherent method to detect and possibly correct this, so I believe this would be a required pre-processing step using another pipeline. For now, we are qc-ing all scans in studies, and we are deliberately omitting patients/scans that show these problems.
 
To assess this, we currently slice a segmentation and its corresponding T1w and FLAIR on a PDF, and qc these on a grading scale. We would be curious to see how you do it, and if you have any, please kindly share your experience using LST-AI on scans with motion/noise.

Feel free to reopen, if you would like to discuss!

**Comment by MMSchmitgen** [comment]
Hi @jqmcginnis,

thank you for your answer. :)

Could you please add some detail on how you do QC at the moment? As far as I got it, you are visually inspecting a segmentation and its corresponding T1w and FLAIR in parallel slice by slice and rate it on a grading scale. Am I correct and could you give an example on how your grading scale looks like?
Our idea (for now) is to have the data visually inspected and rated by two independent neuroradiologists, using a grading scale like in the paper attached (Motion: None < Mild < Moderate < Severe). What do you think about this approach?
Another idea is to make use of automated QC implemented in CAT12 (https://neuro-jena.github.io/cat12-help/#qc) during segmentation for T1 and FLAIR images and have a look at the IQR-ratings for T1 and noise-ratings only for FLAIR. We are not sure, if CAT12 correctly handles FLAIR images (it complains about resolution being too low and drops a warning message saying that it is a non-T1 contrast) though... Again, I would love to hear your opinion on this approach.
Would it be possible to implement some kind of automated QC (maybe based on the CAT12-procedure) in future versions of LST-AI? I think this would improve comparability between studies using LST-AI a lot and the community would greatly appreciate it.

Cheers and thanks a lot,
Mike

[Blumenthal_etal_2002_Motion.pdf](https://github.com/user-attachments/files/16246160/Blumenthal_etal_2002_Motion.pdf)

**Comment by twiltgen** [comment]
Hi @MMSchmitgen ,

You are correct. We currently display five equally spaced slices of each image type (T1w, FLAIR, segmentation) on one PDF page, and then we scroll through all the cases. Hence, we visually assess the image and segmentation quality based on these slices displayed in the PDF. We grade the images/segmentation with either a “1” for sufficiently good quality or a “0” for insufficient quality. The zero grade is only given to images with obvious artifacts (e.g., motion, cropped images, susceptibility artifacts, …) and to segmentations in which significantly large MS lesions would not be segmented or non-brain tissue would be segmented.

The QC in CAT12 is very interesting and could serve as an inspiration for future automated QC workflows. However, we have no extensive experience with that approach, making it difficult to give suggestions.

I agree the field would definitely benefit from an automated QC, but for now, we do not plan to integrate it into LST-AI. Maybe we will come up with an automated standalone Python-based QC in the future.

Cheers,
Tun

**Comment by MMSchmitgen** [comment]
Hi @twiltgen ,

excellent, thanks a lot for the info. So we will go for visual inspection, too.

If you plan to build some standalone automated QC, feel free to contact me - I would be happy to help, if I can.

Cheers,
Mike
