### ISSUE TITLE
Lesion probability maps

### ISSUE THREAD

**Issue by hippocampo** [CompImg/LST-AI#17]
Thanks very much to the developers for making this terrific software! I have a feature request, which is to make the lesion probability maps available, prior to applying the binarization threshold. These maps could be useful for a variety of applications. Thank you!

**Comment by jqmcginnis** [comment]
Hi @hippocampo,

@twiltgen and I have been discussing the steps of this feature request, and will develop it during the course of August.

Cheers,

- JM

**Comment by twiltgen** [comment]
Hi @hippocampo ,
we have now integrated the option to save the lesion probability maps in LST-AI. You only have to add the flag "--probability_map" (along with the --temp flag) and then you can find the probability maps in the specified temp folder. We hope this is the feature you were looking for. We have also updated the Readme with more info.
We will close the issue for now, but if you have any feedback, which we would be happy to hear about, you can always re-open it. 
Cheers,
TW
