### ISSUE TITLE
Conda installation and test running 

### ISSUE THREAD

**Issue by Giorgioum** [CompImg/LST-AI#25]
Hi everyone, I've managed to install LST-AI on Conda virtual env. 
After ,I tried to do a test:

`(lst_env) giorgio@giorgio-XPS-15-9530:~$  lst --t1 /home/giorgio/Desktop/t1.nii.gz --flair /home/giorgio/Desktop/flair.nii.gz --output /home/giorgio/Desktop/results --temp /mnt/data/lst/processing`

but there was this output:

``###########################

Thank you for using LST-AI. If you publish your results, please cite our paper:
Wiltgen T, McGinnis J, Schlaeger S, Kofler F, Voon C, Berthele A, Bischl D, Grundl L, Will N, Metz M, Schinz D, Sepp D, Prucker P, Schmitz-Koep B, Zimmer C, Menze B, Rueckert D, Hemmer B, Kirschke J, Mühlau M, Wiestler B. LST-AI: A Deep Learning Ensemble for Accurate MS Lesion Segmentation. NeuroImage: Clinical, Volume 42, 2024. https://doi.org/10.1016/j.nicl.2024.103611.
###########################

Looking for model weights in /home/giorgio/LST-AI/LST_AI.
Downloading data...
Traceback (most recent call last):
  File "/home/giorgio/anaconda3/envs/lst_env/bin/lst", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/giorgio/LST-AI/LST_AI/lst", line 125, in <module>
    download_data(path=os.path.dirname(__file__))
  File "/home/giorgio/LST-AI/LST_AI/utils.py", line 27, in download_data
    data = response.read()
  File "/home/giorgio/anaconda3/envs/lst_env/lib/python3.10/http/client.py", line 482, in read
    s = self._safe_read(self.length)
  File "/home/giorgio/anaconda3/envs/lst_env/lib/python3.10/http/client.py", line 633, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(377487360 bytes read, 10332980 more expected)``

Anyone know how to solve it or if I miss something in installation step?
Thanks in advance!

**Comment by jqmcginnis** [comment]
Hey @Giorgioum,

Thanks for trying out LST-AI! :slightly_smiling_face:

It seems like the model weights download was incomplete. Could you try deleting the partially downloaded weights file (e.g., lst_data.zip or similar) from your directory and then re-running the lst command?

Let us know if this resolves the issue, and feel free to share any further feedback!

- Julian

**Comment by Giorgioum** [comment]
This is the result:

`Looking for model weights in /home/giorgio/LST-AI/LST_AI.
Images need to be skull-stripped. Processing with HD-BET.
Traceback (most recent call last):
  File "/home/giorgio/anaconda3/envs/lst_env/bin/lst", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/giorgio/LST-AI/LST_AI/lst", line 298, in <module>
    mni_registration(t1w_atlas,
  File "/home/giorgio/LST-AI/LST_AI/register.py", line 40, in mni_registration
    subprocess.run(shlex.split(rigid_call), check=True)
  File "/home/giorgio/anaconda3/envs/lst_env/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/giorgio/anaconda3/envs/lst_env/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/giorgio/anaconda3/envs/lst_env/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'greedy'`

But I've set greedy

**Comment by Giorgioum** [comment]
I tried method 1 to install greedy this time `chmod +x greedy
mkdir ~/bin
mv greedy ~/bin
export PATH="$HOME/bin:$PATH"
mkdir: cannot create directory ‘/home/giorgio/bin’: File exists`

If i go in ...home/bin there is the greedy foulder, but the greedy program is in home/LST-AI/LST_AI/binaries

**Comment by Giorgioum** [comment]
I resolve it by renaming "greedy" directory in "greedy_d" and then moving greedy program file in ~/bin. 
Before there was a conflict, in fact after `chmod +x ~/bin/greedy` greedy was identified as directory.
If I run `greedy` now, there are no problems, thanks a lot!

But now I've problem with HD-BET 😅, i'll try fix by myself or if is useful to the community I'll post a new issue and close this. Thanks again!

**Comment by Giorgioum** [comment]
Now It works fine!

So first of all I step in this error : `/home/giorgio/anaconda3/envs/lst_env/bin/hd-bet:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('HD-BET==1.0')`
and I solved it whit `pip install setuptools==60`.

And second in this,  `ImportError: cannot import name 'deprecated' from 'typing_extensions' (/home/giorgio/anaconda3/envs/lst_env/lib/python3.10/site-packages/typing_extensions.py)`. Very similar to https://github.com/CompImg/LST-AI/issues/22.
I solved it by running in terminal `conda search torch` --> I found pytorch 2.0.1 --> run `conda install pytorch==2.0.1`.
