### ISSUE TITLE
LST-AI installation error

### ISSUE THREAD

**Issue by jhkang0526** [CompImg/LST-AI#4]
Hi, 

I'm having an issue installing your LST-AI repository. I followed the instructions in the Readme, but I'm getting the following error:

`Installing collected packages: LST-AI
  Running setup.py develop for LST-AI
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [8 lines of output]
        running develop
        /home/kjh/anaconda3/envs/lst/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /home/kjh/anaconda3/envs/lst/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running egg_info
        creating LST_AI.egg-info
        error: could not create 'LST_AI.egg-info': Permission denied
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
    running develop
    /home/kjh/anaconda3/envs/lst/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/kjh/anaconda3/envs/lst/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    creating LST_AI.egg-info
    error: could not create 'LST_AI.egg-info': Permission denied
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
`

I've attached a screenshot of the installation instructions for reference.

Can you help me troubleshoot this issue?

Thanks,
Junghwa Kang.

<img width="861" alt="Screenshot 2023-12-12 at 10 26 56 PM" src="https://github.com/CompImg/LST-AI/assets/58097369/fc64d10e-41f8-47fe-80fb-bd7bc9ed5d67">

**Comment by jqmcginnis** [comment]
Hi @jhkang0526 

Thank you very much for giving LST-AI a try! Given your terminal output, I sense that there are some problems with privileges, i.e.

The error message "could not create 'LST_AI.egg-info': Permission denied" typically indicates a permission-related issue on your computer's file system. Here are some potential sources of this error:

1. User Permissions: The most common cause is that your user account doesn't have the necessary permissions to write to the directory where you're trying to create the 'LST_AI.egg-info'. This can happen if you're working in a directory that requires administrator or root privileges.
2. File System Restrictions: The directory you're working in might be read-only, or there could be specific file system restrictions (like NTFS file permissions on Windows) that prevent writing to that directory.

To trouble shoot your problem further, could you please let us know?

1. Which OS are you using?
2. Did you follow the steps in the Readme?

Thank you very much!

Julian

**Comment by jhkang0526** [comment]
Thank you for your quick response to my question.

1. My OS is Linux Ubuntu 22.04.
2. The following set of commands works fine: I encountered an error in step 4 when I started the `pip install -e .` command.

I appreciate your help and support.

Thanks again,
Junghwa Kang

**Comment by jqmcginnis** [comment]
HI @jhkang0526  - are you running these commands in a conda environment, or a venv? Is your conda base environment activated? I.e. does it say `(base) username@pc: `?

**Comment by jqmcginnis** [comment]
@jhkang0526 Did this work? :slightly_smiling_face:

**Comment by jqmcginnis** [comment]
@jhkang0526 I am closing this issue as there hasn't been any activity in the last four weeks, and I am assuming the issues have been resolved. If you are still facing problems, I am happy to help! :slightly_smiling_face: 

Just re-open this issue and we will chip in.

Thank you,
Julian
