### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by BennoGesierich** [CompImg/LST-AI#8]
Hi Julian,

I got an error during building the Docker file in line 74:

Dockerfile:74
--------------------
  72 |               -DCMAKE_BUILD_TYPE=Release ..
  73 |     # run build process
  74 | >>> RUN make -j ${BUILD_JOBS}
  75 |     RUN make install
  76 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c make -j ${BUILD_JOBS}" did not complete successfully: exit code: 2

Do I have to create the variable BUILD_JOBS somehow or any idea why this happens?

All the best,
Benno

**Comment by jqmcginnis** [comment]
@BennoGesierich thank you for reporting the bug. We are currently working on a fix, and I will notify you as soon as possible, once this has been resolved :+1:

**Comment by MMSchmitgen** [comment]
> Hi Julian,
> 
> I got an error during building the Docker file in line 74:
> ## Dockerfile:74
> ## 72 | -DCMAKE_BUILD_TYPE=Release ..
> 73 | # run build process
> 74 | >>> RUN make -j ${BUILD_JOBS}
> 75 | RUN make install
> 76 |
> 
> ERROR: failed to solve: process "/bin/sh -c make -j ${BUILD_JOBS}" did not complete successfully: exit code: 2
> 
> Do I have to create the variable BUILD_JOBS somehow or any idea why this happens?
> 
> All the best, Benno

Same issue, different line:

--------------------
  49 |     # Run CMake to configure and build VTK
  50 |     RUN cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
  51 | >>> RUN make -j ${BUILD_JOBS}
  52 |     RUN make install
  53 |
--------------------
ERROR: failed to solve: process "/bin/sh -c make -j ${BUILD_JOBS}" did not complete successfully: exit code: 2

Cheers,
Mike

**Comment by jqmcginnis** [comment]
Dear @BennoGesierich @MMSchmitgen 

I am sorry to see that I totally forgot about this issue, thanks for reminding me. 

Indeed, we need to pass the variable as an argument to the build instruction:

`docker build --platform linux/amd64 --build-arg BUILD_JOBS=8 .`

However, I noticed that the ITK build fails for me - I will try to work on a fix asap!

Thanks again for letting us know!

Cheers,

Julian

**Comment by MMSchmitgen** [comment]
> Dear @BennoGesierich @MMSchmitgen
> 
> I am sorry to see that I totally forgot about this issue, thanks for reminding me.
> 
> Indeed, we need to pass the variable as an argument to the build instruction:
> 
> `docker build --platform linux/amd64 --build-arg BUILD_JOBS=8 .`
> 
> However, I noticed that the ITK build fails for me - I will try to work on a fix asap!
> 
> Thanks again for letting us know!
> 
> Cheers,
> 
> Julian

Dear Julian,

you are welcome, thank you for having a look into the issue.

Cheers,
Mike

**Comment by tobrace** [comment]
> Dear @BennoGesierich @MMSchmitgen
> 
> I am sorry to see that I totally forgot about this issue, thanks for reminding me.
> 
> Indeed, we need to pass the variable as an argument to the build instruction:
> 
> `docker build --platform linux/amd64 --build-arg BUILD_JOBS=8 .`
> 
> However, I noticed that the ITK build fails for me - I will try to work on a fix asap!
> 
> Thanks again for letting us know!
> 
> Cheers,
> 
> Julian

Dear Julian,

I tried to use this build instruction, but it still pump up the same error  "The command '/bin/sh -c make -j ${BUILD_JOBS}' returned a non-zero code: 2"

Cheers,
Young

**Comment by jqmcginnis** [comment]
Hi @tobrace, I am currently debugging it and will try to provide an update asap! Thank you very much for the patience :) (In the mean time feel free to use the container from docker hub if you can )

**Comment by dcfragoso** [comment]
Hello Julian,

I tried run the new dockerfile released yesterday and i found the following error!

```dockerfile
 => ERROR [49/57] RUN git checkout v1.1.0                                                       0.1s
------
 > [49/57] RUN git checkout v1.1.0:
0.119 error: pathspec 'v1.1.0' did not match any file(s) known to git
------
Dockerfile:114
--------------------
 112 |     WORKDIR /custom_apps/lst_directory/LST-AI
 113 |     RUN git pull origin main
 114 | >>> RUN git checkout v1.1.0
 115 |     
 116 |     # pip or pip3 depending on your system
--------------------
ERROR: failed to solve: process "/bin/sh -c git checkout v1.1.0" did not complete successfully: exit code: 1

``` 

Do you have any idea what occurred?

Thank you in advance!
Cheers,
Diego.

**Comment by jqmcginnis** [comment]
@dcfragoso Sorry for that; I hadn't pushed the most recent changes.  (Also, I thought I was working on a branch, not main :see_no_evil: given that I still want to verify the changes, and if the built container does what it should be doing)
 
In any case, it's building for AMD64 on my end now - as the building process and uploading (also for ARM64) take some time, I expect the new containers to be up soon. I will test them thoroughly and let you know when everything's validated.
I will keep the issue open until everything is resolved and validated!

**Comment by dcfragoso** [comment]
Thank you very much @jqmcginnis!!

**Comment by jqmcginnis** [comment]
@dcfragoso @BennoGesierich @MMSchmitgen @tobrace 

I just pushed the ARM64 (which takes foreeeveeer to build) to dockerhub. I hope this solves this issue, and everybody can utilize (or build) our docker containers now. Please let me know if this works, and if not please re-open the issue :slightly_smiling_face:  Thank you guys for all the patience and help, Julian
