### ISSUE TITLE
How can I use LST-AI without GPU?

### ISSUE THREAD

**Issue by sj-choi** [CompImg/LST-AI#9]
I tried to run LST-AI. 
However, I got GPU related error message. How I can I run this with out GPU, but CPU only?
Is there any options in the python script not to use GPU?

Thank you,
-SC

**Comment by jqmcginnis** [comment]
Hi @sj-choi 

There is :+1:  Please specify via the `--device` option. Here is the description on how to use the flag:

`--device: Provide an integer value (e.g. 0) for a GPU ID or cpu if you do not have access to a GPU.`

Does this help?
